### ISSUE TITLE
is Generator function.sent Meta Property dead?

### ISSUE THREAD

**Issue by dou4cc** [allenwb/ESideas#20]

**Comment by ljharb** [comment]
this repo is a collection of ideas, not a single proposal.

**Comment by dou4cc** [comment]
OK, s/this proposal/these proposals/g

**Comment by dou4cc** [comment]
well, is [Generator function.sent Meta Property](https://github.com/allenwb/ESideas/blob/master/Generator%20metaproperty.md) dead?

**Comment by ljharb** [comment]
No, that's been extracted out to https://github.com/tc39/proposal-function.sent (which you can determine by referencing the master proposal list https://github.com/tc39/proposals)

**Comment by dou4cc** [comment]
good

i came from http://kangax.github.io/compat-table/esnext/

**Comment by ljharb** [comment]
Thanks, I've updated that.

**Comment by dou4cc** [comment]
had better add a redirector in this repo
