### ISSUE TITLE
Can you give some code example for ES7MetaProps

### ISSUE THREAD

**Issue by popomore** [allenwb/ESideas#3]
Especially `function.next`, can't understand without code.

**Comment by bmeck** [comment]
```
function* addTogether(left=0) {
  let right = function.next;
  return left + right;
}
assert( addTogether(1).next(2) == 3 );
```

This is a good example since the first `.next` has no left hand for the argument in the generator code (normally it would replace a yield expression) you could use `function.next` to get the value that was passed in.

**Comment by popomore** [comment]
Thx, that's good.
